name: asterisk_links
description: Flutter plugin to support Universal Links (iOS)/App Links (Android).
version: 0.0.1
homepage: https://github.com/jiahan-wu/asterisk_links

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.asterisk_links
        pluginClass: AsteriskLinksPlugin
      ios:
        pluginClass: AsteriskLinksPlugin